# 4 TO-DO - Task

Please complete all the problem listed below.

## 4.1 Exercise on Functions:

### Task - 1:
Create a Python program that converts between different units of measurement.
- The program should:
  1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
  2. Ask the user to input the value to be converted.
  3. Perform the conversion and display the result.
  4. Handle potential errors, such as invalid input or unsupported conversion types.
- Requirements:
  1. Functions: Define at least one function to perform the conversion.
  2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
  3. User Input: Prompt the user to select the conversion type and input the value.
  4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.
- Conversion Options:
  1. Length:
     - Convert meters (m) to feet (ft).
     - Convert feet (ft) to meters (m).
  2. Weight:
     - Convert kilograms (kg) to pounds (lbs).
     - Convert pounds (lbs) to kilograms (kg).
  3. Volume:
     - Convert liters (L) to gallons (gal).
     - Convert gallons (gal) to liters (L).

In [ ]:
def convert(option, num):
  """Converts between different units of measurement.

  Args:
    option: An integer representing the conversion option.
    num: A float representing the value to be converted.

  Returns:
    The converted value, or None if the conversion option is invalid.
  """
  if option == 1:
    return num * 3.28084
  elif option == 2:
    return num / 3.28084
  elif option == 3:
    return num * 2.20462
  elif option == 4:
    return num / 2.20462
  elif option == 5:
    return num / 3.78541
  elif option == 6:
    return num * 3.78541
  else:
    return None

try:
  option = int(input('''Enter an option:
                    Conversion Options:
                      Length:
                      1)Convert meters (m) to feet (ft).
                      2)Convert feet (ft) to meters (m).
                      Weight:
                      3)Convert kilograms (kg) to pounds (lbs).
                      4)Convert pounds (lbs) to kilograms (kg).
                      Volume:
                      5)Convert liters (L) to gallons (gal).
                      6)Convert gallons (gal) to liters (L).
                '''))

  if option in range(1, 7):
    val = float(input('Enter the value to be converted: '))
    result = convert(option, val)
    if result is not None:
      print(f"The converted value is: {result}")
    else:
      print("Invalid conversion option.")
  else:
    print("Invalid input. Please enter a number between 1 and 6.")

except ValueError:
  print("Invalid input. Please enter a number.")
except Exception as e:
  print(f"An error occurred: {e}")

### Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
- The Program should:
  1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers).
  2. Ask the user to input a list of numbers (separated by spaces).
  3. Perform the selected operation and display the result.
  4. Handle potential errors, such as invalid input or empty lists.
- Requirements:
  1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).
  2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).
  3. User Input: Prompt the user to select the operation and input the list of numbers.
  4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and return value.

In [ ]:
def calculate_sum(numbers):
  """Calculates the sum of a list of numbers without using built-in functions.

  Args:
    numbers: A list of numbers.

  Returns:
    The sum of the numbers in the list.
  """
  total = 0
  for number in numbers:
    total += number
  return total

def calculate_average(numbers):
  """Calculates the average of a list of numbers without using built-in functions.

  Args:
    numbers: A list of numbers.

  Returns:
    The average of the numbers in the list.
  """
  if not numbers:
    return 0
  total = calculate_sum(numbers)
  return total / len(numbers)

def find_maximum(numbers):
  """Finds the maximum value in a list of numbers without using built-in functions.

  Args:
    numbers: A list of numbers.

  Returns:
    The maximum value in the list.
  """
  if not numbers:
    return None  # Handle empty lists
  maximum = numbers[0]
  for number in numbers:
    if number > maximum:
      maximum = number
  return maximum

def find_minimum(numbers):
  """Finds the minimum value in a list of numbers without using built-in functions.

  Args:
    numbers: A list of numbers.

  Returns:
    The minimum value in the list.
  """
  if not numbers:
    return None
  minimum = numbers[0]
  for number in numbers:
    if number < minimum:
      minimum = number
  return minimum

def main():
  """Main function to handle user input and perform operations."""
  try:
    operation = input("Choose an operation (sum, average, maximum, minimum): ")
    numbers_str = input("Enter a list of numbers separated by spaces: ")
    numbers = [float(num) for num in numbers_str.split()]

    if operation == "sum":
      result = calculate_sum(numbers)
    elif operation == "average":
      result = calculate_average(numbers)
    elif operation == "maximum":
      result = find_maximum(numbers)
    elif operation == "minimum":
      result = find_minimum(numbers)
    else:
      print("Invalid operation.")
      return

    print(f"The result is: {result}")

  except ValueError:
    print("Invalid input. Please enter numbers only.")
  except Exception as e:
    print(f"An error occurred: {e}")

if __name__ == "__main__":
  main()

## 4.2 Exercise on List Manipulation:

### 1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
- Requirements:
  - Define a function `extract_every_other(lst)` that takes a list `lst` as input and returns a new list containing every other element from the original list.
  - Example: For the input `[1, 2, 3, 4, 5, 6]`, the output should be `[1, 3, 5]`.

In [ ]:
def  extract_every_other(lst):
  """Extracts every other element from a list, starting from the first element.

  Args:
    lst: The input list
  Returns:
    A list of every other element from the input list.
  """
  return lst[::2]


print(extract_every_other([1, 2, 3, 4, 5, 6]))

[1, 3, 5]


### 2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.
- Requirements:
  - Define a function `get_sublist(lst, start, end)` that takes a list `lst`, a starting index `start`, and an ending index `end` as input and returns the sublist from start to end (inclusive).
  - Example: For the input `[1, 2, 3, 4, 5, 6]` with `start=2` and `end=4`, the output should be `[3, 4, 5]`.

In [ ]:
def get_sublist(lst, start, end):
  """Returns a sublist from a given list, starting from a specified index and ending at another specified index.

  Args:
    lst: The input list.
    start: The starting index (inclusive).
    end: The ending index (inclusive).

  Returns:
    A sublist from the input list, or an empty list if the indices are invalid.
  """
  if start < 0 or end >= len(lst) or start > end:
    return []
  sublist = []
  for i in range(start, end + 1):
    sublist.append(lst[i])
  return sublist

lst = [1, 2, 3, 4, 5, 6]
start = 2
end = 4
sublist = get_sublist(lst, start, end)
print(sublist)

### 3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
- Requirements:
  - Define a function `reverse_list(lst)` that takes a list `lst` and returns a reversed list using slicing.
  - Example: For the input `[1, 2, 3, 4, 5]`, the output should be `[5, 4, 3, 2, 1]`.

In [ ]:
def reverse_list(lst):
  """Reverses a list using slicing.

  Args:
    lst: The input list.

  Returns:
    A reversed list.
  """
  return lst[::-1]

lst = [1, 2, 3, 4, 5]
reversed_lst = reverse_list(lst)
print(reversed_lst)

[5, 4, 3, 2, 1]


### 4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting sublist.
- Requirements:
  - Define a function `remove_first_last(lst)` that takes a list `lst` and returns a sublist without the first and last elements using slicing.
  - Example: For the input `[1, 2, 3, 4, 5]`, the output should be `[2, 3, 4]`.

In [ ]:
def remove_first_last(lst):
  """Removes the first and last elements of a list and returns the resulting sublist.

  Args:
    lst: The input list.

  Returns:
    A sublist without the first and last elements, or an empty list if the input list has fewer than 2 elements.
  """
  if len(lst) < 2:
    return []
  return lst[1:-1]

lst = [1, 2, 3, 4, 5]
new_lst = remove_first_last(lst)
print(new_lst)

[2, 3, 4]


### 5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
- Requirements:
  - Define a function `get_first_n(lst, n)` that takes a list `lst` and an integer `n` as input and returns the first n elements of the list using slicing.
  - Example: For the input `[1, 2, 3, 4, 5]` with `n=3`, the output should be `[1, 2, 3]`.


In [ ]:
def get_first_n(lst, n):
    """Extracts the first n elements from a list using slicing.

    Args:
        lst: The input list.
        n: The number of elements to extract.

    Returns:
        A new list containing the first n elements of the input list.
    """
    return lst[:n]


lst = [1, 2, 3, 4, 5]
n = 3
first_n_elements = get_first_n(lst, n)
print(first_n_elements)

[1, 2, 3]


### 6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
- Requirements:
  - Define a function `get_last_n(lst, n)` that takes a list `lst` and an integer `n` as input and returns the last n elements of the list.
  - Example: For the input `[1, 2, 3, 4, 5]` with `n=2`, the output should be `[4, 5]`.


In [ ]:
def get_last_n(lst, n):
  """Extracts the last n elements of a list using slicing.

  Args:
    lst: The input list.
    n: The number of elements to extract from the end.

  Returns:
    A new list containing the last n elements of the input list.
  """
  return lst[-n:]

lst = [1, 2, 3, 4, 5]
n = 2
last_n_elements = get_last_n(lst, n)
print(last_n_elements)

[4, 5]


### 7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.
- Requirements:
  - Define a function `reverse_skip(lst)` that takes a list `lst` and returns a new list containing every second element starting from the second-to-last, moving backward.
  - Example: For the input `[1, 2, 3, 4, 5, 6]`, the output should be `[5, 3, 1]`.


In [ ]:
def reverse_skip(lst):
  """Extracts a list of elements in reverse order, skipping one element in between.

  Args:
    lst: The input list.

  Returns:
    A new list containing every second element starting from the second-to-last, moving backward.
  """
  return lst[-2::-2]

lst = [1, 2, 3, 4, 5, 6]
reversed_skipped_lst = reverse_skip(lst)
print(reversed_skipped_lst)

[5, 3, 1]


## 4.3 Exercise on Nested List:

### 1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.
- Requirements:
  - Define a function `flatten(lst)` that takes a nested list `lst` and returns a flattened version of the list.
  - Example: For the input `[[1, 2], [3, 4], [5]]`, the output should be `[1, 2, 3, 4, 5]`.


In [ ]:
def flatten(lst):
  """
  Takes a nested list list returns a flattened version of the list.
  Args: Lst: The input list.
  Returns: A flattened list.
  """
  flat_lst = []
  for e in lst:
    flat_lst.extend(e)
  return flat_lst

lst = [[1, 2], [3, 4], [5]]
flat_lst = flatten(lst)
print(flat_lst)


[1, 2, 3, 4, 5]


### 2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
- Requirements:
  - Define a function `access_nested_element(lst, indices)` that takes a nested list `lst` and a list of indices `indices`, and returns the element at that position.
  - Example: For the input `lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]` with `indices = [1, 2]`, the output should be `6`.


In [ ]:
def access_nested_element(lst, indices):
  """
  Takes a nested list and a list of indices
  Args: lst: The input list. indices: The list of indices.
  Returns: The element at the specified position.
  """
  # for index in indices:
  #   lst = lst[index]
  # return lst
  return lst[indices[0]][indices[1]]

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
element = access_nested_element(lst, indices)
print(element)


6


### 3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
- Requirements:
  - Define a function `sum_nested(lst)` that takes a nested list `lst` and returns the sum of all the elements.
  - Example: For the input `[[1, 2], [3, [4, 5]], 6]`, the output should be `21`.

In [ ]:
def sum_nested(lst):
  """
  Calculates the sum of all the numbers in a nested list.
  Args: lst: The input list.
  Returns: The sum of all the numbers in the list.
  """
  total = 0
  for element in lst:
      if isinstance(element, list):
          total += sum_nested(element)
      elif isinstance(element, (int, float)):
          total += element
  return total

total = sum_nested([[1, 2], [3, [4, 5]], 6])
print(total)

21


### 4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
- Requirements:
  - Define a function `remove_element(lst, elem)` that removes `elem` from `lst` and returns the modified list.
  - Example: For the input `lst = [[1, 2], [3, 2], [4, 5]]` and `elem = 2`, the output should be `[[1], [3], [4, 5]]`.

In [ ]:
def remove_element(lst, elem):
  """
  Removes all occurrences of a specific element from a nested list.
  Args: lst: The input list. elem: The element to remove.
  Returns: The modified list.
  """
  for i in range(len(lst)):
    if isinstance(lst[i], list):
      remove_element(lst[i], elem)
    elif lst[i] == elem:
      lst.remove(elem)
  return lst

lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
modified_lst = remove_element(lst, elem)
print(modified_lst)

[[1], [3], [4, 5]]


### 5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
- Requirements:
  - Define a function `find_max(lst)` that takes a nested list `lst` and returns the maximum element.
  - Example: For the input `[[1, 2], [3, [4, 5]], 6]`, the output should be `6`.

In [ ]:
def find_max(lst):
  """
  Finds the maximum element in a nested list.
  Args: lst: The input list.
  Returns: The maximum element.
  """
  max_val = 0

  def find_max_recursive(lst, current_max):
    """Helper function to recursively find the maximum."""
    for element in lst:
      if isinstance(element, list):
        current_max = find_max_recursive(element, current_max)
      elif isinstance(element, (int, float)):
        if element > current_max:
          current_max = element
    return current_max

  max_val = find_max_recursive(lst, max_val)
  return max_val

lst = [[1, 2], [3, [4, 5]], 6]
max_element = find_max(lst)
print(max_element)

6


### 6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
- Requirements:
  - Define a function `count_occurrences(lst, elem)` that counts the occurrences of `elem` in the nested list `lst`.
  - Example: For the input `lst = [[1, 2], [2, 3], [2, 4]]` and `elem = 2`, the output should be `3`.


In [ ]:
def count_occurences(lst, elem):
  """
  Counts the occurrences of an element in a nested list.
  Args: lst: The input list. elem: The element to count.
  Returns: The number of occurrences.
  """
  count = 0
  for element in lst:
    if isinstance(element, list):
      count += count_occurences(element, elem)
    elif element == elem:
      count += 1
  return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
occurrences = count_occurences(lst, elem)
print(occurrences)


3


### 7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
- Requirements:
  - Define a function `deep_flatten(lst)` that takes a deeply nested list `lst` and returns a single flattened list.
  - Example: For the input `[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]`, the output should be `[1, 2, 3, 4, 5, 6, 7, 8]`.


In [ ]:
def deep_flatten(lst):
  """
  Flattens a list of lists of lists into a single list.
  Args: lst: The input list.
  Returns: The flattened list.
  """
  flat_lst = []
  for element in lst:
    if isinstance(element, list):
      flat_lst.extend(deep_flatten(element))
    else:
      flat_lst.append(element)
  return flat_lst

lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flat_lst = deep_flatten(lst)
print(flat_lst)

[1, 2, 3, 4, 5, 6, 7, 8]


### 8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
- Requirements:
  - Define a function `average_nested(lst)` that takes a nested list `lst` and returns the average of all the elements.
  - Example: For the input `[[1, 2], [3, 4], [5, 6]]`, the output should be `3.5`.

In [ ]:
def average_nested(lst):
  """
  Calculates the average of all elements in a nested list.
  Args: lst: The input list.
  Returns: The average
  """
  flat_lst = []
  for element in lst:
    if isinstance(element, list):
      flat_lst.extend(deep_flatten(element))
    else:
      flat_lst.append(element)
  sum = 0
  for i in flat_lst:
    sum += i
  return sum/len(flat_lst)
lst = [[1, 2], [3, 4], [5, 6]]
print(average_nested(lst))



3.5


# 10 To-Do - NumPy

Please complete all the problems listed below:

In [ ]:
import numpy as np



## 10.1 Basic Vector and Matrix Operation with Numpy.

### Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value. {Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array. {Hint: np.zeros_like}
5. Return a new array of ones with same shape and type as a given array. {Hint: np.ones_like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array. {Hint: np.array()}

In [ ]:
# Initialize an empty array with size 2X2.
empty_arr = np.empty((2,2))
print("\nEmpty array with size 2X2:")
print(empty_arr)

# Initialize an all one array with size 4X2.
one_array = np.ones((4,2))
print("\nAll one array with size 4X2:")
print(one_array)

# Return a new array of given shape and type, filled with fill value
filled_array = np.full((3, 3), 7, dtype=int)
print("\nFilled array with shape (3, 3) and fill value 7:")
print(filled_array)

# Return a new array of zeros with same shape and type as a given array
a = np.array([[1, 2, 4], [3, 4, 5]])
zeros_like_array = np.zeros_like(a)
print("\nArray of zeros with same shape and type as 'a':")
print(zeros_like_array)

# Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(a)
print("\nArray of ones with same shape and type as 'a':")
print(ones_like_array)

# Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nNumPy array from list:", numpy_array)


Empty array with size 2X2:
[[0. 0.]
 [0. 0.]]

All one array with size 4X2:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled array with shape (3, 3) and fill value 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

Array of zeros with same shape and type as 'a':
[[0 0 0]
 [0 0 0]]

Array of ones with same shape and type as 'a':
[[1 1 1]
 [1 1 1]]

NumPy array from list: [1 2 3 4]


### Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint: np.arange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8. {Hint: look for np.reshape()}
3. Create a 3X3 identity matrix. {Hint: np.eye()}
4. Create a random array of size 30 and find the mean of the array. {Hint: check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
# Create an array with values ranging from 10 to 49
array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:", array_10_to_49)

# Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape((3, 3))
print("\n3x3 matrix from 0 to 8:")
print(matrix_3x3)

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 identity matrix:")
print(identity_matrix)

# Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:")
print("\nMean of the random array:", mean_value)

# Create a 10x10 array with random values and find min/max
random_array_10x10 = np.random.random((10, 10))
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()
print("\n10x10 array with random values:")
print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

# Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with 5th element replaced with 1:")
print(zero_array)

# Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:", reversed_arr)

# Create a 2d array with 1 on border and 0 inside
array_2d = np.ones((5, 5))  # Example size 5x5
array_2d[1:-1, 1:-1] = 0
print("\n2d array with 1 on border and 0 inside:")
print(array_2d)

# Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\nCheckerboard pattern:")
print(checkerboard)

Array from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:

Mean of the random array: 0.42363413114010023

10x10 array with random values:

Minimum value: 0.021604833632329568
Maximum value: 0.9996527419924658

Zero array with 5th element replaced with 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array: [0 4 0 0 2 1]

2d array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint: try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# Add the two arrays (x and y)
addition_result = x + y
print("Addition Result (x + y):")
print(addition_result)

# Subtract the two arrays (x and y)
subtraction_result = x - y
print("\nSubtraction Result (x - y):")
print(subtraction_result)

# Multiply the array (x) with an integer (3)
multiplication_result = x * 3
print("\nMultiplication Result (x * 3):")
print(multiplication_result)

# Find the square of each element of the array (x)
square_result = x ** 2
print("\nSquare of each element of x:")
print(square_result)

# Find the dot product between:
#    - v and w
dot_product_vw = np.dot(v, w)
print("\nDot product of v and w:", dot_product_vw)

#    - x and v
dot_product_xv = np.dot(x, v)
print("Dot product of x and v:", dot_product_xv)

#    - x and y
dot_product_xy = np.dot(x, y)
print("Dot product of x and y:")
print(dot_product_xy)

# Concatenate:
#    - x and y along row
concatenate_xy_row = np.concatenate((x, y), axis=0)
print("\nConcatenation of x and y along row:")
print(concatenate_xy_row)

#    - v and w along column
v = np.reshape((v), (2, 1))
w = np.reshape((w), (2, 1))
concatenate_vw_col = np.concatenate([v, w], axis=1)
print("\nConcatenation of v and w along column:")
print(concatenate_vw_col)

# Concatenate x and v
concatenate_xv = np.concatenate((x, v))


Addition Result (x + y):
[[ 6  8]
 [10 13]]

Subtraction Result (x - y):
[[-4 -4]
 [-4 -3]]

Multiplication Result (x * 3):
[[ 3  6]
 [ 9 15]]

Square of each element of x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y:
[[19 22]
 [50 58]]

Concatenation of x and y along row:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along column:
[[ 9 11]
 [10 12]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 1

### Problem - 4: Matrix Operations:
- For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A⁻¹ = I.
2. Prove AB ≠ BA.
3. Prove (AB)ᵀ = BᵀAᵀ.


In [ ]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])
shape = np.shape(A)

# Prove A.A⁻¹ = I
I = np.eye(shape[1])
inverse = np.linalg.inv(A)

dot_prod = np.dot(A,inverse)
dot_prod = np.round(dot_prod, decimals=10)

print('\nProve A.A⁻¹ = I')
print(dot_prod)
print(I)
print(f"Both matrices are equal: {np.array_equal(dot_prod, I)}")

# Prove AB ≠ BA.
AB = np.dot(A,B)
BA = np.dot(B,A)
print('\nProve AB ≠ BA')
print(AB)
print(BA)
print(f"Both matrices are not equal: {not np.array_equal(AB, BA)}")

# Prove (AB)ᵀ = BᵀAᵀ
print('\n')
ABT = np.transpose(np.dot(A,B))
print("AB Transpose: \n",ABT)
BT = np.transpose(B)
AT = np.transpose(A)
BTA = np.dot(BT,AT)
print("B Transpose A Transpose: \n",BTA)
print(f"Both matrices are equal: {np.array_equal(ABT, BTA)}")


Prove A.A⁻¹ = I
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
Both matrices are equal: True

Prove AB ≠ BA
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
Both matrices are not equal: True


AB Transpose: 
 [[23 51]
 [13 29]]
B Transpose A Transpose: 
 [[23 51]
 [13 29]]
Both matrices are equal: True


- Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

- Now: solve the above equation using np.linalg.inv function. {Explore more about "linalg" function of Numpy}

In [ ]:
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution:")
print("x =", X[0])
print("y =", X[1])
print("z =", X[2])

Solution:
x = 2.0
y = 1.0
z = -2.0


## 10.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
   - Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure and Print the time taken for this operation.
   - Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.


In [ ]:
import random
import time

list1 = random.choices(range(1, 2000), k=1_000_000)
list2 = random.choices(range(1, 5000), k=1_000_000)

# Using list
s_time = time.time()
result = [x+y for x,y in zip(list1, list2)]
e_time = time.time()
print(f"(Python Lists): {e_time - s_time:.4f} sec")

# Using Numpy
list1 = np.array(list1)
list2 = np.array(list2)
s_time = time.time()
result = list1 + list2
e_time = time.time()
print(f"(Numpy Arrays): {e_time - s_time:.4f} sec")

(Python Lists): 0.1001 sec
(Numpy Arrays): 0.0028 sec


2. Element-wise Multiplication
   - Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000. Measure and Print the time taken for this operation.
   - Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.



In [ ]:
import random
import time

list1 = random.choices(range(1, 2000), k=1_000_000)
list2 = random.choices(range(1, 5000), k=1_000_000)

# Using list
s_time = time.time()
result = [x*y for x,y in zip(list1, list2)]
e_time = time.time()
print(f"(Python Lists): {e_time - s_time:.4f} sec")

# Using Numpy
list1 = np.array(list1)
list2 = np.array(list2)
s_time = time.time()
result = list1 * list2
e_time = time.time()
print(f"(Numpy Arrays): {e_time - s_time:.4f} sec")

(Python Lists): 0.1181 sec
(Numpy Arrays): 0.0071 sec


3. Dot Product
   - Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and Print the time taken for this operation.
   - Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [ ]:
import random
import time

list1 = random.choices(range(1, 2000), k=1_000_000)
list2 = random.choices(range(1, 5000), k=1_000_000)

# Using list
s_time = time.time()
result = [x*y for x,y in zip(list1, list2)]
e_time = time.time()
print(f"(Python Lists): {e_time - s_time:.4f} sec")

# Using Numpy
list1 = np.array(list1)
list2 = np.array(list2)
s_time = time.time()
result = np.dot(list1,list2)
e_time = time.time()
print(f"(Numpy Arrays): {e_time - s_time:.4f} sec")

(Python Lists): 0.2059 sec
(Numpy Arrays): 0.0027 sec



4. Matrix Multiplication
   - Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
   - Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
matrix_size = 1000

matrix1_list = [[i + j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2_list = [[i * j for j in range(matrix_size)] for i in range(matrix_size)]

# Python Lists
start_time = time.time()
result_matrix_list = [[sum(a * b for a, b in zip(row_a, col_b))
                      for col_b in zip(*matrix2_list)] for row_a in matrix1_list]
end_time = time.time()
print(f"\n(Python Lists): {end_time - start_time:.4f} seconds")

# NumPy Arrays
matrix1_array = np.array(matrix1_list)
matrix2_array = np.array(matrix2_list)
start_time = time.time()
result_matrix_array = np.dot(matrix1_array, matrix2_array)
end_time = time.time()
print(f"(NumPy Arrays): {end_time - start_time:.4f} seconds")


(Python Lists): 211.3727 seconds
(NumPy Arrays): 1.6273 seconds
